services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    networks:
      - proxy
    volumes:
      - vaultwarden:/data
    environment:
      - ADMIN_TOKEN=${ADMIN_PWD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vw.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.vw.entrypoints=websecure"
      - "traefik.http.routers.vw.tls.certresolver=le"

networks:
  proxy:
    external: true